#!/bin/bash

# use node_modules/.bin first
PATH=./node_modules/.bin:$PATH

# exit on any error
set -e

# create the release
lerna version --yes

# publish it to npm
lerna publish from-git  \
  --dist-tag alpha      \
  --yes
