name: Release
on:
  push:
    branches:
      - alpha
      # - main
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: lts/*

      - name: npm install
        run: npm i

      - name: Git Identity
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN_ACTION }}@github.com/${{ github.repository }}

      - name: ensure NPM credentials
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          node ./create-npmrc
          npm whoami

      - name: lerna version
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git reset --hard
          lerna version --yes

      - name: build
        run: npm run build

      - name: lerna publish
        run: lerna publish from-package --dist-tag alpha --no-verify-access --no-git-reset --yes
